### ISSUE TITLE
textarea at supabase/ui

### ISSUE THREAD

**Issue by florian-lefebvre** [supabase/ui#158]
Looking at https://ui.supabase.com/?path=/docs/data-input-input--text-area, I think that only the height should be editable and not the width. It would be also great to put a max-height and a min-height.

**Comment by MildTomato** [comment]
Hey @florian-lefebvre 

I believe the only way you could adjust the height (without `rows`) is:

```js
<Input.TextArea
  style={{
    height: 128px
    // anything else you like
  }}
/>
```

any kind of style can be passed on here - so max-height and min-height could also just be an inline style.
I don't think it would be that useful to restrict / remove being able to implement any kind of inline css with `style`.

I'd recommend using `rows` for the height, since it uses the font line height and useful for hinting exactly how many rows of text the user is expected to input.

It is quite bad how this is implemented as the `style` prop is passed to the Input container (which has the error message, input and optional label) and the `className` is passed to the outer wrapper - which is super confusing and not really what you'd expect. It was a bit of a hack just so you could easily control the width of the input.

on another note: Might also be beneficial if it was possible to change the `style` and `className` of specifically the input inside the component, the input container, and then also the entire div wrapper that contains everything.

**Comment by MildTomato** [comment]
Sorry for anyone looking at our storybook website.

It makes no sense, especially for subcomponents like Input.TextArea - none of the examples seem to show correctly and there's missing API info for them.

I'm working on fixing this today :D

**Comment by MildTomato** [comment]
I'm going to close this for now. 
If the above isn't sufficient or someone has a more elegant way of dealing with this, please reopen.
