### ISSUE TITLE
Feat: Show change password view on <Auth/> component

### ISSUE THREAD

**Issue by jin-exists** [supabase/ui#193]
I’m trying to work out a flow for a forgotten password in my application, but the Auth component’s change password view doesn’t seem to be linked up to anything.

**Comment by MildTomato** [comment]
Could you provide some more details on this?

There is currently only a 'forgotten_password' view in the Auth component, which can be shown by clicking 'Forgot your password?'.

The Auth example might not be working currently on [ui.supabase.io](http://ui.supabase.io), we should probably fix this as it's useful to play around with in the docs examples.

**Comment by jin-exists** [comment]
The forgotten password view works fine, it sends an email to change your password. The problem comes when you click that link. I would expect that upon clicking on the link, that a view shows up to actually change the password, or at the very least for the component to have the ability to have a prop passed to it to show said view.

In the code for the component (line 463, https://github.com/supabase/ui/blob/develop/src/components/Auth/Auth.tsx) it appears that the view is already there, called updatePassword. Problem is, the view doesn’t seem to be in the viewMap (line 20 in the component) so there’s no way for it to show. There might be some additional code needed, as I believe there needs to be a token passed to actually change the password.

**Comment by YashKandalkar** [comment]
@jin-exists If you're talking about the user actually changing the password then after the email has been sent the supabase app  receives an access_token, and a `type=recovery` parameter in the url ([docs](https://supabase.io/docs/reference/javascript/reset-password-email#notes)). This can be used to update the password of the user. 

And the Auth component in this repo which is linked to a supabase app redirects users to ui.supabase.com, which gets the access_token and other params there but nothing is done from that. 

The [react-todo-list](https://github.com/supabase/supabase/blob/master/examples/react-todo-list/) in the main supabase repo's example has this flow implemented, you can take a look.


Sending a recovery email: [link](https://github.com/supabase/supabase/blob/3dee8d9c2f1860bcc938763cb11a7304d41b62fc/examples/react-todo-list/src/components/Auth.js#L35)

Reading token and other parameters from the URL: [link](https://github.com/supabase/supabase/blob/3dee8d9c2f1860bcc938763cb11a7304d41b62fc/examples/react-todo-list/src/components/Home.js#L12)
(Here [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) can be used probably to get all params from url, rather than splitting)

**Comment by jin-exists** [comment]
@YashKandalkar Thanks for the details on how the reset flow works Supabase side, it really helped!

I found a solution and am posting here for anybody else trying to build a reset flow. The JS library (not sure if it's the UI library or the main Supabase library) appears to already be parsing the URL and firing a `PASSWORD_RECOVERY` event on the `supabase.auth.onAuthStateChange` listener.

I'm using Next.js so I added the listener into my `_app.js` file and had it redirect with a query parameter on the `PASSWORD_RECOVERY` event.
```
useEffect(() => {
  // Used to prevent redirection out of the authentication page during a password reset
  let preventAppPush = false

  const { data: authListener } = supabase.auth.onAuthStateChange((event) => {
    if (event === 'SIGNED_IN') setTimeout(() => !preventAppPush && router.push('/app'), 500)
    if (event === 'SIGNED_OUT') router.push('/?view=sign_in')
    if (event === 'PASSWORD_RECOVERY') {
      preventAppPush = true
      router.push('/?view=update_password')
    }
    if (event === 'USER_UPDATED') setTimeout(() => router.push('/?view=sign_in'), 1000)
  })

  return () => {
    authListener.unsubscribe()
  }
}, [])
```

Then in my auth page I added some conditional JSX to show the `UpdatePassword` component. Even though the component isn't in the VIEWS, it still is exported with dot notation for some reason so I was able to use the component. I'll make a PR to get the component properly in the VIEWS.
```
{router.query.view === 'update_password' ? (
    <Auth.UpdatePassword supabaseClient={supabase} />
  ) : (
    <Auth supabaseClient={supabase} providers={['google']} view={router.query.view || 'sign_in'} />
)}
```
