### ISSUE TITLE
Feat: Toast

### ISSUE THREAD

**Issue by kiwicopple** [supabase/ui#92]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be awesome to improve our current toasts.

## Describe the solution you'd like

Ideally one where we can present details errors to the user.

## Describe alternatives you've considered

This is nice: https://react-hot-toast.com/

## Additional context

https://twitter.com/notlilj/status/1352069821819625474

**Comment by MildTomato** [comment]
Nice to have would be have a loading / progress bar type of toast message.

Probably good to consider also just using react-hot-toast in this library and using the [custom styling option](https://react-hot-toast.com/docs/styling)

**Comment by jonthomp** [comment]
I'm going to start working on this

**Comment by MildTomato** [comment]
@jonthomp assigned to you!

**Comment by MildTomato** [comment]
@jonthomp Hey Jon, some stuff I found using react-hot-toast today.

I thought I'd be able to quickly replace some of our toast messages with react-hot-toast, and basically just wrap the thing in [radix-portal](https://radix-ui.com/primitives/docs/utilities/portal) so that it renders on top of our Supabase UI overlays (SidePanel, Modal... and so on) but I found that react-hot-toast gets rendered before the overlays and they all have the same z-index, which is the [highest z-index value available](https://github.com/radix-ui/primitives/blob/ceeb027884a110611467d91287baf47cf6fccfdf/packages/react/portal/src/Portal.tsx#L8). So the toast messages always render beneath the overlays.

My workaround was to use react-hot-toast like this:

```js
/* app.js */

import { Toaster, ToastBar } from 'react-hot-toast'
import * as Portal from '@radix-ui/react-portal'

<Portal.Root className="portal--toast">
  <Toaster />
</Portal.Root>
```

```css
/* style.css */

div[data-radix-portal]:not(.portal--toast) {
  /* 
  override z-index to be lower than radix value of 2147483647 
  except for the toast portal
  */
  z-index: 2147483646 !important;
}
```

It's a bit hacky, but then the toast messages are always rendered on top.
![Screenshot 2021-06-07 at 18 32 26](https://user-images.githubusercontent.com/8291514/121002235-b76cb300-c7be-11eb-8e0b-da5036f7ee3c.png)

Looks like Radix are also looking at making a Toast component we could use in future, or help out with.
https://github.com/radix-ui/primitives/issues/386

**Comment by jonthomp** [comment]
@MildTomato sorry for my delay, had some things to deal with, jobs to apply for, and got distracted by React 18.

Thanks for the tip, I added it in.
Also, good news re Radix Toast component, although it's on hold atm, their last plans were to also use `react-hot-toast` so migrating in the future will hopefully be easier.

https://user-images.githubusercontent.com/660222/122443592-a6c6f480-cf97-11eb-8b76-69e43cb3a42c.mp4
